[package]
name = "protobuf-compiler"
version = "0.1.0"
authors = ["ensonmj <ensonmj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
